### ISSUE TITLE
Hoverable doesn't work on Mobile

### ISSUE THREAD

**Issue by GeorgeWL** [codypearce/material-bread#185]
Not sure if intended, cross-platform implies not, but I don't know for sure.

My assumption was that on mobile, if you (~~Mobile equivalent to onMouseover~~ onTouchEnter) it would have some form of animation?

https://codypearce.github.io/material-bread/?path=/story/utils-hoverable--animation

Tested in Chrome for Android and Firefox Nightly for Android

**Comment by codypearce** [comment]
That's a good point. I implemented that on tooltips (click to activate on mobile, hover on web), I'm trying to think of scenario where you would want hover on web but not click on mobile. Thinking about it, it probably should be the default to click to activate hover on mobile.

**Comment by GeorgeWL** [comment]
I can't imagine any at all tbh.

I'd convert Hover to click on mobile, and possibly just add a comment about it.

I'd argue that Hover on mobile it's unreliable at best, and tbh, it goes against most good practice guides from what I've seen.
