### ISSUE TITLE
Require Cycle warnings

### ISSUE THREAD

**Issue by alburdette619** [codypearce/material-bread#195]
**Describe the bug**
When importing from the library, many `Require cycle` warnings are displayed.

**To Reproduce**
1. Create an RN project and install `material-bread`
2. Import from `material-bread`
3. Start app on either platform and observe the warnings.

**Expected behavior**
No warnings to be shown on the user's app based on this library.

**Screenshots**
<img width="404" alt="Screen Shot 2019-06-06 at 9 34 25 AM" src="https://user-images.githubusercontent.com/22638838/59036969-4b0cf100-883e-11e9-8f9d-fcdd1bf79dea.png">

**Smartphone (please complete the following information):**
 - Device: iPhone X / Pixel 1 XL
 - OS: iOS 12.2 / Android 9

**Additional context**
Fix: The import of components from `src/index.js` is what is causing these warnings as its sets up a cyclic requirement.  The components need to be imported from their own directories.

**Comment by codypearce** [comment]
Closed by #196

**Comment by dorw123** [comment]
@codypearce The issue still reproduces with both cycle warnings and nativeDriver.
