### ISSUE TITLE
Docs: ProgressCircle - wrong import

### ISSUE THREAD

**Issue by alburdette619** [codypearce/material-bread#204]
**Describe the bug**
The import in the docs for `ProgressCircle` say `ProgressBar`

**To Reproduce**
1. Go to the `ProgressCircle` docs page

**Expected behavior**
The correct import should be shown.

**Screenshots**
<img width="396" alt="Screen Shot 2019-06-20 at 12 21 11 PM" src="https://user-images.githubusercontent.com/22638838/59865166-63106480-9356-11e9-9ce2-369516342b94.png">

**Additional context**
I will put in a fix for this shortly.

**Comment by codypearce** [comment]
fixed in #205
