### ISSUE TITLE
TextFieldLabel: Wrong position on focused/filled

### ISSUE THREAD

**Issue by alburdette619** [codypearce/material-bread#206]
**Describe the bug**
When a TextField is focused or filled, the label x translation is variable based on string length.  The longer the string the more to the right the label is pushed.  Short strings seem to line up almost correctly.

**To Reproduce**
1. Render TextFields (outlined/filled) with variable length labels
2. Observe that when focused/filled the label's x position is wrong.

**Expected behavior**
The TextField should follow Material Design and position the label accordingly.

**Screenshots**
<img width="743" alt="Screen Shot 2019-06-20 at 7 49 29 PM" src="https://user-images.githubusercontent.com/22638838/59888232-ba352a00-9394-11e9-859e-a7d0cf7b82dc.png">

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 12.2

**Additional context**
Will be putting in a fix very shortly.

**Comment by codypearce** [comment]
Closed by #207
