### ISSUE TITLE
TextInput alignment iOS/Android

### ISSUE THREAD

**Issue by mgonzalezs** [codypearce/material-bread#216]
**Describe the bug**

**To Reproduce**
1. Implement a `TextField` with label
2. Compare the alignment on iOS and Android and observe the error

**Expected behavior**
Typed text should be consistent on iOS and Android

**Screenshots**
Left: Android
Right: iOS
![image](https://user-images.githubusercontent.com/41348080/61233951-ceecaf80-a6ff-11e9-9241-16e5bf79122a.png)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12
 - Device: Nexus 6
 - OS: API 28

**Comment by codypearce** [comment]
Closed by #217
