### ISSUE TITLE
List Item onPress called when onAnimationEnd

### ISSUE THREAD

**Issue by mgonzalezs** [codypearce/material-bread#218]
**Describe the bug**
- The ListItem onPress prop is being called when onAnimationEnd is called. So even if you are scrolling the  onPress is always called

**To Reproduce**
1. Create a list with ListItem objects
2. Try to scroll and verify that the onPress event is being called 

**Expected behavior**
The onPress function must be called when the user intends to do an onPress, not when the user is scrolling

**Screenshots**

![FCBH-470](https://user-images.githubusercontent.com/41348080/61265051-c70f2880-a75c-11e9-95f7-91a4acb2fe22.gif)

**Smartphone:**
 - Device: iPhone X
 - OS: 12.2

**Comment by codypearce** [comment]
Closed by #219
