### ISSUE TITLE
Fab inside Fabspeed dial is overlaped by appbarbottom 

### ISSUE THREAD

**Issue by dann1609** [codypearce/material-bread#221]
**Describe the bug**
First Fab button inside FabSpeedDial is overlapped by app bar bottom. No matter if I add zIndex or elevation half bottom is under appbarbottom

**To Reproduce**
1. Just use SpeedDial example at [appbarbottom example](https://github.com/codypearce/material-bread/issues/url) On android device. 

**Expected behavior**
See Fab bottom over the bottom menu.

**Screenshots**
<img width="458" alt="Screen Shot 2019-07-18 at 6 14 03 PM" src="https://user-images.githubusercontent.com/7472461/61559737-fdd09180-aa2f-11e9-881b-a1a24e1e9c72.png">

**Desktop:**
 React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 17.84 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 25.0.2, 28.0.3, 29.0.1
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Smartphone:**
 - Device: Genymotion-Samsung Galaxy S8
 - OS: 8.0 API 26

**Comment by codypearce** [comment]
@dann1609 I'm having trouble reproducing this

<img width="289" alt="Android Emulator - Nexus_5_API_27:5554 2019-07-22 01-17-58" src="https://user-images.githubusercontent.com/12564956/61617098-e3103f80-ac1e-11e9-92ed-949f50801d56.png">
<img width="306" alt="Android Emulator - Nexus_5_API_27:5554 2019-07-22 01-19-39" src="https://user-images.githubusercontent.com/12564956/61617100-e3103f80-ac1e-11e9-86d5-d45c5f24af12.png">

Perhaps it's specific to Genymotion?

**Comment by dann1609** [comment]
@codypearce I also tested in a physical device and see the issue

device: red 4x
android version: 8.1.0

**Comment by dann1609** [comment]
Also genimotion Google Nexus S device. Please let me know which one device did you use to save previous screenshots.

**Comment by codypearce** [comment]
Fixed #226
