### ISSUE TITLE
ListItem doesn't truncate text

### ISSUE THREAD

**Issue by RyanMcDonald** [codypearce/material-bread#224]
**Describe the bug**
ListItem should truncate text if it spans more than one line. Or maybe this should be configurable?

**To Reproduce**
1. Pass a long string for the `text` or `secondaryText` props.
2. See that the text spans multiple lines.

**Expected behavior**
The text should be truncated with an ellipsis.

**Screenshots**
![image](https://user-images.githubusercontent.com/2695365/61587594-d964da00-ab41-11e9-9d22-48f45114bd8c.png)

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: [e.g. iOS 12.2]

**Comment by codypearce** [comment]
I think it should probably be configurable, there are examples of both truncated and wrapping secondary text in lists in the Material Design Docs https://material.io/design/components/lists.html#types

Probably best solution to create a prop for `secondaryTextProps` that takes an object and spreads props onto the base `<Text />` so a user can have manual control over the ellipse. What do you think?

**Comment by RyanMcDonald** [comment]
@codypearce That sounds reasonable to me! You would need `textProps` and `secondaryTextProps`.

I took a quick stab at this, hoping it would be that simple, but there was an issue with the layout when `media` or `icon` was introduced, and I didn't have time to debug it properly. The text was getting pushed to the right and expanding past its container.

**Comment by alburdette619** [comment]
@RyanMcDonald @codypearce I have this one on my radar and have time on my project for it. I'll submit a PR shortly.

**Comment by alburdette619** [comment]
Additionally @codypearce Material only shows at max 2 lines for the sub, so we should cap that out on the text by default.

**Comment by codypearce** [comment]
closed by #245
