### ISSUE TITLE
TextField - using `leadingIcon` prop results in a Yellowbox

### ISSUE THREAD

**Issue by ds8k** [codypearce/material-bread#238]
**Describe the bug**
Providing an icon to TextField in the `leadingIcon` prop causes a Yellowbox to appear stating that an invalid prop of `object` was passed when it expected a boolean

**To Reproduce**
```
<TextField
  containerStyle={styles.commonMarginTop}
  type="outlined"
  label="Email Address"
  leadingIcon={
    <Icon name="email" size={24} color={colors.iconInactive} />
  }
/>
```

**Expected behavior**
TextField renders with no warnings

**Screenshots**
<img width="374" alt="Screen Shot 2019-07-31 at 9 15 41 AM" src="https://user-images.githubusercontent.com/4458812/62215556-30a25000-b375-11e9-844f-8474412e9029.png">

**Comment by thyagarajarahul** [comment]
What is the solution to this problem?

**Comment by ds8k** [comment]
@thyagarajarahul If you install bread from the latest commit you'll have my change that fixes this yellowbox
