### ISSUE TITLE
FAB in Appbar bottom onPress not triggered in Android works fine in iOS

### ISSUE THREAD

**Issue by thyagarajarahul** [codypearce/material-bread#272]

**Comment by thyagarajarahul** [comment]
Is there any solution for this problem?

**Comment by codypearce** [comment]
@thyagarajarahul  This PR might solve the issue https://github.com/codypearce/material-bread/pull/273

**Comment by thyagarajarahul** [comment]
This PR has nothing to do with RN or your Lib. Can you suggest me something else?

**Comment by codypearce** [comment]
@thyagarajarahul The link above is for a PR on this library for RN, that directly addresses the title of this issue.
