### ISSUE TITLE
Elevation for Material Components not visible in android.

### ISSUE THREAD

**Issue by thyagarajarahul** [codypearce/material-bread#278]
Cards, Switch, Paper etc have no elevation visible in Android but works fine in iOS. Elevation has to be defined in order for visibility. None shown by default. Shadow property doesn't work in Android.

**Comment by codypearce** [comment]
@thyagarajarahul 
1.  According to the Material Doc, Switches don't have elevations, though it could be added if we need it.
<img width="975" alt="Selection controls - Material Design 2019-09-08 03-57-38" src="https://user-images.githubusercontent.com/12564956/64487309-993ee100-d1ed-11e9-8e2d-0ce5eb13fe72.png">

2. As far as I can tell Paper's shadow property works on Android
<img width="370" alt="Android Emulator - Nexus_5_API_27:5554 2019-09-08 03-48-59" src="https://user-images.githubusercontent.com/12564956/64487257-ef5f5480-d1ec-11e9-969e-0627e78a6054.png">

3. Cards do appear to have an issue with rendering shadows
<img width="341" alt="Android Emulator - Nexus_5_API_27:5554 2019-09-08 04-02-23" src="https://user-images.githubusercontent.com/12564956/64487304-8d531f00-d1ed-11e9-8dac-c1bb23d2be3e.png">

This has been patched by this https://github.com/codypearce/material-bread/commit/eb810464754fcf5ee3785043f74c2cba2316c0b9

This will be included in the next version, however you can test it now by pointing your the npm package to the repo.
