### ISSUE TITLE
[SSR] Material Bread x NextJS

### ISSUE THREAD

**Issue by hedikasmanto** [codypearce/material-bread#291]
**Describe your feature request**
Provide Support React SSR using NextJS

**Comment by hedikasmanto** [comment]
Here the repo https://github.com/hedikasmanto/material-bread-next-example

and ListItem / Hoverableissue u can found on #292

**Comment by codypearce** [comment]
@hedikasmanto This works great! I created a PR for fixing the Hoverable layout #297. I'd love to include your example repo in the documentation, would that be ok?

**Comment by hedikasmanto** [comment]
Yes.. Please include the example in the documentation, and I will close this issue
