### ISSUE TITLE
Slider: Add customization for markers and track

### ISSUE THREAD

**Issue by alburdette619** [codypearce/material-bread#295]
Currently there is no way to adjust styling for the Slider's track or markers.  The sizes are set statically with no props to change it.

**Proposed solution**
Add three props `markerSize`, `trackHeight`, and `trackStyle`.  `trackHeight` would always override `trackStyle`, but either should set height.  All calculations based on static track height and marker size will now be based on these props such that the component renders correctly given any input.

**NOTE:** PR incoming soon

**Comment by codypearce** [comment]
closed by #296
