### ISSUE TITLE
[WEB] Storybook web not working

### ISSUE THREAD

**Issue by fortezhuo** [codypearce/material-bread#308]
**Describe the bug**
Storybook web not working

**To Reproduce**
1. Clone the repo
2. Run npm run (yarn) test:generate-output
3. Run npm run (yarn) storybook-web
4. Storybook load and blank white screen appears

**Expected behavior**
Storybook Web should can be used for dev env

**Comment by codypearce** [comment]
It looks like this is some sort of `5.2.3` Storybook issue https://github.com/storybookjs/storybook/issues/6014

![Storybook 2019-10-14 00-00-23](https://user-images.githubusercontent.com/12564956/66733818-a450e680-ee15-11e9-8aca-b12b1427a2bc.png)

I tried creating a fresh project and forcing the version I have on my current version `5.0.6` and I get a bunch of other errors for `emotion-theming` which is more issues from Storybook.

Upgrading to the very latest `5.3.0-alpha.17` Storybook and I get this issue https://github.com/storybookjs/storybook/issues/6337

Overall kind of frustrating, I'll have to look more into this over the next week.

**Comment by codypearce** [comment]
closed by #345
