### ISSUE TITLE
Icons not working with Expo

### ISSUE THREAD

**Issue by serhanozcan** [codypearce/material-bread#312]
Material Bread not found expo icons file path. So getting errors using with ExpoCLI. Anyone have solution or fix ?

**Comment by codypearce** [comment]
@serhanozcan Can you share what errors you're getting?

**Comment by codypearce** [comment]
I've created a repo using Expo and Expo web  https://github.com/codypearce/material-bread-expo-example

The essential setup is describe here
https://material-bread.org/getting-started/expo#setup

Basically, we need to provide the MaterialIcon font to the browser. Generate the `index.html` to insert the font in the head. Run the following and select index.html :

```
expo customize:web
```

Next we need to download the font file, `MaterialIcons.ttf`, here https://github.com/oblador/react-native-vector-icons/blob/master/Fonts/MaterialIcons.ttf.  Add this file to a new `web` folder at the root.

Finally, go to the index.html and add the following to the bottom of the `<style>` element.
```
@font-face {
    src: url(./MaterialIcons.ttf);
    font-family: MaterialIcons;
}
```

Now you can run the following and start adding components with icons.
![MB Expo 2019-12-08 07-18-54](https://user-images.githubusercontent.com/12564956/70393147-0e13e980-199c-11ea-9368-9374be441416.png)
