### ISSUE TITLE
Build fails on expo web

### ISSUE THREAD

**Issue by jascaniojah** [codypearce/material-bread#317]
After installed and configured, the build fails for web.

LOG OUTPUT:
/.../..../node_modules/material-bread/dist/Components/AppbarBottom/AppbarBottom.svg.js
Module not found: Can't resolve 'react-native-svg' in '/.../..../design-system-rn/node_modules/material-bread/dist/Components/AppbarBottom'

**To Reproduce**
1. Expo init
2. install material-bread
3. expo start -w

Should i configure a webpack.config.js file? Can anyone help me?

**Comment by codypearce** [comment]
@jascaniojah You need to install `react-native-svg`, just run 
```
npm i react-native-svg
```
And it should be working 
![image](https://user-images.githubusercontent.com/12564956/70391397-891fd480-1989-11ea-878a-0f90be64013c.png)

You can see a working example here
https://github.com/codypearce/material-bread-expo-example
