### ISSUE TITLE
RTL: Sliders should still go left-to-right

### ISSUE THREAD

**Issue by ds8k** [codypearce/material-bread#318]
**Describe the bug**
RTL languages still expect things like sliders (ex: track players) to go left-to-right, as mentioned in this article written by Spotify: https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps

Currently the slider is mirrored when a RN app is set to an RTL language. Additionally, I have to slide in the opposite direction to move the marker "forward"

**To Reproduce**
- Add slider to an app that supports RTL languages
- Switch to RTL language

**Expected behavior**
- Slider maintains left-to-right

**Screenshots**
![Screen Shot 2019-10-17 at 12 51 33 PM](https://user-images.githubusercontent.com/4458812/67030196-e790ab00-f0dc-11e9-9a90-94ec9024dc42.png)

I've got a branch on my fork that I'll be submitting as a PR that resolves this issue

**Comment by ds8k** [comment]
This is resolved in PR #319

**Comment by codypearce** [comment]
closed by #319
