### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by skubakdj** [codypearce/material-bread#322]
Is TypeScript currently supported? I may try to PR a typings file in the next few weeks if not.

This project is seriously awesome, thanks so much!

**Comment by codypearce** [comment]
@skubakdj Thanks, glad you find it useful! Typescript is currently not supported but it's been on my todo list for while, if you're willing make a PR for it that'd be awesome.

**Comment by punisher97** [comment]
Hi, i working in Monorepo material-bread is amazing, but i too need typescript support :(, while i sahre my monorepo template, thanks @codypearce 
[template monorepo with material-bread!](https://github.com/punisher97/react-native-web-monorepo)
![react-native-web-monorepo](https://raw.githubusercontent.com/punisher97/react-native-web-monorepo/master/screenshot.png)

**Comment by skubakdj** [comment]
Working on the type definitions now :grin:

**Comment by punisher97** [comment]
Thanks!!! please share 👍 i could help you if you want @skubakdj

**Comment by skubakdj** [comment]
@punisher97 I should have a PR up this week (hopefully in the next few days) and could definitely use some help testing
