### ISSUE TITLE
Value of type boolean supplied to TextFieldLabel

### ISSUE THREAD

**Issue by bcgilliom** [codypearce/material-bread#364]
**Describe the bug**
PropType warning for TextField label value type

**To Reproduce**
1. Use TextField filled as a controlled component (supply a value prop) and set a label
3. enter text
2. cause input to lose focus
3. see warning

**Expected behavior**
Looks like the `value` prop should be a bool on TextFieldLabel, possibly called `hasValue`?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 13

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Sim
 - OS: 13

**Additional context**
Very minor - will make a PR if I have time, or let me know if there's a workaround - will suppress yellow box warning for now

**Comment by codypearce** [comment]
closed by #367
