### ISSUE TITLE
[New] Add ability to disable safe area view in Drawer on iOS

### ISSUE THREAD

**Issue by bcgilliom** [codypearce/material-bread#365]
**Describe your feature request**

On iOS, a SafeAreaView is applied automatically, without a way to disable it via props. I'd like to propose we add a way to disable that.

**Context**
this interferes with the one used by react-navigation, and it seems to work correctly when disabled

**Proposed solution**
make `needsSafeAreaView` a prop that defaults to true on iOS

**Comment by codypearce** [comment]
closed by #366
