### ISSUE TITLE
[New] More documentation is needed with vue-native.

### ISSUE THREAD

**Issue by eaglejs** [codypearce/material-bread#380]
**Describe your feature request**
Material Bread website has a lot of documentation on how to implement its components with react, but what about vue or vue-native? It would be great if we can document components in these frameworks as well.

**Context**
Material-bread website has instructions on how to make MB work on vue-native. I did notice that the format is a bit different for elements. for example, `<AppBar />` is the element you use to use AppBar, but in vue-native, it is `<mb-appbar>`. I have looked at the code ever since in order to find the right element that I need. but even then it is still confusing to me because things like the `<Select />` has a prop called menuItems, and the way it is set in react is clear, but in vue-native. I tried `<mb-select ... menuItems="languages" />` and each time it tells me that my languages variable is not of type array, but in my code, it is an array. (Perhaps the way I am trying to pass the variable to the template is wrong, and i'm missing something very important here.

[https://gist.github.com/eaglejs/8e84f1a5dd726cb897a2cfa808d42777](url)

**Proposed solution**
I propose that there should be documentation that explains or provides enough examples to show how to implement these components in vue-native properly. At the very least, show every possible scenario. Some props have camel case because they are multi-worded. camel-cased props are the ones that do not work for me, so I believe I am implementing it incorrectly; however, due to the lack of documentation in vue-native, I have no idea how to implement it the vue-native way. I really do like this component library and I wish to use it in my project! :) Thank you!

**Comment by codypearce** [comment]
Ideally there'd be another tab for each code example for each component showing how to use it in `vue-native`, but I'm not sure how much time I'll have in the near future though. Another concern is that it looks like vue native hasn't been updated since Oct 2019, https://github.com/GeekyAnts/vue-native-core, which makes me question whether the project is still alive and worth supporting. Any thoughts?


>  I tried <mb-select ... menuItems="languages" /> and each time it tells me that my languages variable is not of type array, but in my code, it is an array. (Perhaps the way I am trying to pass the variable to the template is wrong, and i'm missing something very important here.

If you make an example repo I'd be happy to take a closer look, I'm guessing there might some issue with the props being passed to vue native from MB.

**Comment by eaglejs** [comment]
Hey @codypearce Thank you for responding back so quickly!

It was suggested by technical leads to use Vue-native, and I too came to the same conclusion. I am glad you saw it too! I feel very validated, and I can make the case for changing frameworks. I don't want to waste your time on this, but thank you very much for the quick response time! 

If for some reason you feel like you want to know why it's not working for your libraries sake, I'll make a repo real quick and link it here:

https://github.com/eaglejs/mb-vue-native

Thank you very much!
