### ISSUE TITLE
Get value on onPress callback for ToggleButtonGroup

### ISSUE THREAD

**Issue by JakeHadley** [codypearce/material-bread#381]
**Describe the bug**
How does one capture which toggle button was pressed in a toggle button group? I tried adding an `onPress` prop to the `ToggleButtonGroup` component, but didn't receive a value for it...
```
<ToggleButtonGroup
    onPress={val => console.log(val)} //undefined
>
    <ToggleButton />
    <ToggleButton />
</ToggleButtonGroup>
```

**To Reproduce**
1. Add `onPress` prop to ToggleButtonGroup

**Expected behavior**
Get a value back to show which one was pressed.

**Comment by codypearce** [comment]
Looks like that's a bug. The `value` from `ToggleButton` should be passed to the `onPress` of the `ToggleButtonGroup`. 

I've updated this on master, https://github.com/codypearce/material-bread/commit/bdcf3f20628109268801ae73b1868ba3f2a919cd.

You can test this by installing from master if you want.

I'm going to close this issue, but feel free to reopen if the issue persists.
