### ISSUE TITLE
Appbar navigation icon color prop

### ISSUE THREAD

**Issue by JakeHadley** [codypearce/material-bread#384]
**Describe the bug**
I guess this is kind of a bug, but more of a small enhancement. Is there a way to change the color of the navigation icon on the appbar? Just add a prop called `navigationColor` or something so it can be modified? I'm thinking if I have a light colored appbar and want a dark colored icon button.

**Comment by codypearce** [comment]
@JakeHadley You can replace the navigation icon by passing an element into the `navigation` prop.
 

```js
<App
  navigation={<IconButton name="menu" color={isDarkMode ? 'darkblue' : 'white' } /> }
/>
```
