### ISSUE TITLE
Card with and without onPress serves up different renders

### ISSUE THREAD

**Issue by JakeHadley** [codypearce/material-bread#419]
**Describe the bug**
When adding `onPress` prop to a Card component, the styling changes.

**To Reproduce**
Standard component with 
```js
<Card onPress={() => {}}>
  <Text>Hello</Text>
</Card>
``` 
Full return():
```js
    <SafeAreaView
      style={{
        backgroundColor: baseColor, //TODO: Get from theme
        flex: 1
      }}
    >
      {/* Heading  */}
      <Heading translations={translations} />
      <View
        style={{
          borderColor: 'red',
          borderWidth: 2,
          flex: 1,
          alignItems: 'center',
          justifyContent: 'space-around'
        }}
      >
        <Text
          style={{
            color: whiteColor,
            fontSize: RFPercentage(5)
          }}
        >
          Game Settings
        </Text>
        <Card onPress={() => { }}>
          <Text>Hello</Text>
        </Card>
      </View>

    </SafeAreaView>
```

**Screenshots**
Without onPress
![Simulator Screen Shot - iPhone 11 - 2020-07-31 at 13 20 38](https://user-images.githubusercontent.com/35585841/89074374-22dd2d00-d331-11ea-85c4-a4b6520a66de.png)

With onPress
![Simulator Screen Shot - iPhone 11 - 2020-07-31 at 13 20 32](https://user-images.githubusercontent.com/35585841/89074435-3be5de00-d331-11ea-8ec9-a32903f49a73.png)

**Comment by codypearce** [comment]
fixed in #424
